import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideStore } from '@ngrx/store';
import { provideEffects } from '@ngrx/effects';
import { provideToastr } from 'ngx-toastr';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import { authReducer } from './core/store/auth/auth.reducer';
import { AuthEffects } from './core/store/auth/auth.effects';
import {
  LucideAngularModule,
  ArrowLeft,
  Plus,
  Edit2,
  Trash2,
  Check,
  X,
  MapPin,
  Search,
  Filter,
  UserPlus,
  Loader,
  Tags,
  ChevronRight,
  CircleDot,
  LayoutDashboard,
  Laptop,
  ScanLine,
  Users,
  Settings,
  Bell,
  Menu,
  Pencil,
  Camera,
  CameraOff,
  UserCheck,
  CircleCheck,
  Wrench,
  Edit,
  Info,
  Download,
  TriangleAlert,
  Image,
  Save,
  Video,
  VideoOff,
  ChevronUp,
  ChevronDown,
  FileSpreadsheet,
  UploadCloud,
  Type,
  Hash,
  RefreshCw,
  Package,
  UserMinus,
  AlertCircle,
  Edit3,
  User,
  Zap,
  ZapOff,
  History,
  Calendar,
  Clock,
  Lock,
  Scan,
  ArrowUpRight,
  ArrowDownLeft,
  Monitor,
  Smartphone,
  Tablet,
  Tv,
  Printer,
  Server,
  Network,
  MousePointer,
  Cable,
  Headphones,
  HardDrive,
  Armchair,
  Wifi,
  Router,
  Battery,
  Cpu,
  Radio,
  Projector,
  Key,
  Bluetooth,
  Briefcase,
  Layers,
  Component,
  Database,
  Plug,
  Shield,
  Square,
  Upload
} from 'lucide-angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideAnimations(),
    provideToastr({
      timeOut: 3000,
      positionClass: 'toast-top-right',
      preventDuplicates: true,
    }),
    provideStore({ auth: authReducer }),
    provideEffects([AuthEffects]),
    importProvidersFrom(LucideAngularModule.pick({
      ArrowLeft,
      Plus,
      Edit2,
      Trash2,
      Check,
      X,
      MapPin,
      Search,
      Filter,
      UserPlus,
      Loader,
      Tags,
      ChevronRight,
      CircleDot,
      LayoutDashboard,
      Laptop,
      ScanLine,
      Users,
      Settings,
      Bell,
      Menu,
      Pencil,
      Camera,
      CameraOff,
      UserCheck,
      CircleCheck,
      Wrench,
      Edit,
      Info,
      Download,
      TriangleAlert,
      Image,
      Save,
      Video,
      VideoOff,
      ChevronUp,
      ChevronDown,
      FileSpreadsheet,
      UploadCloud,
      Type,
      Hash,
      RefreshCw,
      Package,
      UserMinus,
      AlertCircle,
      Edit3,
      User,
      Zap,
      ZapOff,
      History,
      Calendar,
      Clock,
      Lock,
      Scan,
      ArrowUpRight,
      ArrowDownLeft,
      Monitor,
      Smartphone,
      Tablet,
      Tv,
      Printer,
      Server,
      Network,
      MousePointer,
      Cable,
      Headphones,
      HardDrive,
      Armchair,
      Wifi,
      Router,
      Battery,
      Cpu,
      Radio,
      Projector,
      Key,
      Bluetooth,
      Briefcase,
      Layers,
      Component,
      Database,
      Plug,
      Shield,
      Square,
      Upload
    })),
  ]
};
